/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package segtoolpredictionbreastcancer;

import com.pixelmed.dicom.Attribute;
import com.pixelmed.dicom.AttributeList;
import com.pixelmed.dicom.AttributeTag;
import com.pixelmed.dicom.DicomException;
import com.pixelmed.dicom.TagFromName;
import com.pixelmed.display.SourceImage;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.TreePath;
import net.lingala.zip4j.core.ZipFile;
import net.lingala.zip4j.exception.ZipException;
import net.lingala.zip4j.model.FileHeader;


/**
 *
 * @author Ingenieria
 */
public class frmPredictionBreastCancer extends javax.swing.JFrame {
    
    private static String archivoDICOM;
    private static AttributeList list = new AttributeList();

    /**
     * Creates new form frmPredictionBreastCancer
     */
    public frmPredictionBreastCancer() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(frmPredictionBreastCancer.MAXIMIZED_BOTH);
        rsscalelabel.RSScaleLabel.setScaleLabel(lblSistema,"src/iconos/LogoMedico.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblDirectorio,"src/iconos/LogoDirectorio.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblGioDeveloment,"src/iconos/GioDeveloment.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDirecorioDICOM = new javax.swing.JTree();
        lblPaciente = new javax.swing.JLabel();
        lblElemento = new javax.swing.JLabel();
        lblSistema = new javax.swing.JLabel();
        lblDirectorio = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblIconDICOM = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaDatosDICOM = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnMostrarImagen = new javax.swing.JButton();
        btnNuevoPaciente = new javax.swing.JButton();
        btnBorraPaciente = new javax.swing.JButton();
        btnDetectaContorno = new javax.swing.JButton();
        btnClasificaPatologia = new javax.swing.JButton();
        lblGioDeveloment = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Demo Segtool Prediction Breast Cancer");
        setName("frameSegTool"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DICOM Directorio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jtDirecorioDICOM.setModel(new FileSystemModel(new File("Paciente")));
        jtDirecorioDICOM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDirecorioDICOMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtDirecorioDICOM);

        lblPaciente.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblElemento.setText("Elemento Seleccionado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(lblPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblElemento)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(lblDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Imagen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lblIconDICOM.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtaDatosDICOM.setEditable(false);
        jtaDatosDICOM.setBackground(new java.awt.Color(240, 240, 240));
        jtaDatosDICOM.setColumns(20);
        jtaDatosDICOM.setRows(5);
        jtaDatosDICOM.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane2.setViewportView(jtaDatosDICOM);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnMostrarImagen.setBackground(new java.awt.Color(135, 164, 195));
        btnMostrarImagen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMostrarImagen.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/IcoDatos.png"))); // NOI18N
        btnMostrarImagen.setText("Mostar Datos de Imagen DICOM");
        btnMostrarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarImagenActionPerformed(evt);
            }
        });

        btnNuevoPaciente.setBackground(new java.awt.Color(135, 164, 195));
        btnNuevoPaciente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNuevoPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/IcoAgregaPaciente.png"))); // NOI18N
        btnNuevoPaciente.setText("Cargar Nuevo Paciente ZIP");
        btnNuevoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPacienteActionPerformed(evt);
            }
        });

        btnBorraPaciente.setBackground(new java.awt.Color(135, 164, 195));
        btnBorraPaciente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBorraPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnBorraPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/IcoQuitaPaciente.png"))); // NOI18N
        btnBorraPaciente.setText("Borrar Paciente");
        btnBorraPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorraPacienteActionPerformed(evt);
            }
        });

        btnDetectaContorno.setBackground(new java.awt.Color(135, 164, 195));
        btnDetectaContorno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDetectaContorno.setForeground(new java.awt.Color(255, 255, 255));
        btnDetectaContorno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/IcoContornos.png"))); // NOI18N
        btnDetectaContorno.setText("Detectar Contorno");

        btnClasificaPatologia.setBackground(new java.awt.Color(135, 164, 195));
        btnClasificaPatologia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClasificaPatologia.setForeground(new java.awt.Color(255, 255, 255));
        btnClasificaPatologia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/IcoCalsificacion.png"))); // NOI18N
        btnClasificaPatologia.setText("Clasificar Patología");

        jButton1.setBackground(new java.awt.Color(135, 164, 195));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/IcoLimpiar.png"))); // NOI18N
        jButton1.setText("Limpiar Datos de Imagen DICOM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetectaContorno)
                        .addGap(40, 40, 40)
                        .addComponent(btnClasificaPatologia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGioDeveloment, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnNuevoPaciente)
                        .addGap(38, 38, 38)
                        .addComponent(btnBorraPaciente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrarImagen)
                        .addGap(38, 38, 38))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorraPaciente)
                    .addComponent(btnMostrarImagen)
                    .addComponent(btnNuevoPaciente))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDetectaContorno)
                            .addComponent(btnClasificaPatologia)
                            .addComponent(jButton1))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addComponent(lblGioDeveloment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblIconDICOM, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconDICOM, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(135, 164, 195));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Segtool Prediction Breast Cancer");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingeniería de Software (MSC)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtDirecorioDICOMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDirecorioDICOMMouseClicked
        // TODO add your handling code here:
        //TreePath path = null;
        //path = jtDirecorioDICOM.getSelectionPath(); 
        //System.out.println(path);
        lblPaciente.setText(jtDirecorioDICOM.getSelectionPath().getLastPathComponent().toString());
        archivoDICOM = jtDirecorioDICOM.getLeadSelectionPath().toString().replaceAll("[\\[\\]]", "").replace(", ", "/");
        //System.out.println(archivoDICOM);
    }//GEN-LAST:event_jtDirecorioDICOMMouseClicked

    private void btnMostrarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarImagenActionPerformed
        // TODO add your handling code here:
        String dirFileDICOM = null;
        try {
            File seleccionDICOM = new File(archivoDICOM);
            dirFileDICOM = seleccionDICOM.getAbsolutePath();
            cargarMostrar(seleccionDICOM);
            
            list.read(dirFileDICOM);
            SourceImage img = new com.pixelmed.display.SourceImage(list);
            String datos;
            datos = "Nombre del paciente: " + getTagInformation(TagFromName.PatientName) + "\n"
                  + "ID del paciente: " + getTagInformation(TagFromName.PatientID) + "\n"
                  + "Sintaxis de transferencia: " + getTagInformation(TagFromName.TransferSyntaxUID) + "\n"
                  + "Clase SOP: " + getTagInformation(TagFromName.SOPClassUID) + "\n"
                  + "Modalidad: " + getTagInformation(TagFromName.Modality) + "\n"
                  + "Muestras por píxel: " + getTagInformation(TagFromName.SamplesPerPixel) + "\n"
                  + "Interpretación fotométrica: " + getTagInformation(TagFromName.PhotometricInterpretation) + "\n"
                  + "Espaciado de píxeles: " + getTagInformation(TagFromName.PixelSpacing) + "\n"
                  + "Bits asignados: " + getTagInformation(TagFromName.BitsAllocated) + "\n"
                  + "Bits almacenados: " + getTagInformation(TagFromName.BitsStored) + "\n"
                  + "Bit alto: " + getTagInformation(TagFromName.HighBit) + "\n"        
                  + "Número de cuadros: " + img.getNumberOfFrames() + "\n"
                  + "Anchura: " + img.getWidth() + "\n"
                  + "Altura: " + img.getHeight() + "\n"  
                  + "Es en escala de grises?: " + img.isGrayscale() + "\n"
                  + "Datos de píxeles presentes: " + (list.get(TagFromName.PixelData) != null) + "\n";
                  jtaDatosDICOM.setText(datos);
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btnMostrarImagenActionPerformed

    private void btnNuevoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPacienteActionPerformed
        JFileChooser selectorArchivos = new JFileChooser();
        selectorArchivos.showOpenDialog(this);
        
        String mensajeNuevoPasiente = ""; 
        String selectArchivoZIP = selectorArchivos.getSelectedFile().getAbsolutePath();
        
        try {			
			ZipFile zipFile = new ZipFile(selectArchivoZIP);
		 
//			if (zipFile.isEncrypted()) {		
//				zipFile.setPassword("test123!");
//			}
			
			List fileHeaderList = zipFile.getFileHeaders();			
		
			for (int i = 0; i < fileHeaderList.size(); i++) {
				FileHeader fileHeader = (FileHeader)fileHeaderList.get(i);
				zipFile.extractFile(fileHeader, "Paciente");
			}
			mensajeNuevoPasiente = "Nueva pasiente creada ";
		} catch (ZipException e) {
			mensajeNuevoPasiente = e.toString();
		}
        jtDirecorioDICOM.setModel(new FileSystemModel(new File("Paciente")));
        JOptionPane.showMessageDialog(null, mensajeNuevoPasiente,"Pacientes", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btnNuevoPacienteActionPerformed

    private void btnBorraPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorraPacienteActionPerformed
        // TODO add your handling code here:
        
        int valorBorrado=JOptionPane.showConfirmDialog(null,"Seguro desea eliminar?","Pacientes",JOptionPane.YES_NO_OPTION);
        if (valorBorrado==JOptionPane.YES_OPTION) {
            deleteDir(new File(archivoDICOM));
            jtDirecorioDICOM.setModel(new FileSystemModel(new File("Paciente")));
            JOptionPane.showMessageDialog(null, "Paciente Borrada!","Pacientes", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Paciente No Borrada!","Pacientes", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnBorraPacienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jtaDatosDICOM.setText("");
        lblIconDICOM.setIcon(null);
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public static boolean deleteDir(File dir) {
      if (dir.isDirectory()) {
         String[] children = dir.list();
         for (int i = 0; i < children.length; i++) {
            boolean success = deleteDir (new File(dir, children[i]));
            
            if (!success) {
               return false;
            }
         }
      }
      return dir.delete();
   }
    
    private void cargarMostrar(File seleccionDICOM){
        try {
            SourceImage sImgDICOM = new SourceImage(seleccionDICOM.getAbsolutePath());
            Image ImgDICOM = sImgDICOM.getBufferedImage().getScaledInstance(lblIconDICOM.getWidth(), lblIconDICOM.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon iconDICOM = new ImageIcon(ImgDICOM);
            lblIconDICOM.setIcon(iconDICOM);       
            
        } catch (IOException | DicomException ex) {
            Logger.getLogger(frmPredictionBreastCancer.class.getName()).log(Level.SEVERE, null, ex);
        }          
    }    

    private static String getTagInformation(AttributeTag attrTag) {
            return Attribute.getDelimitedStringValuesOrEmptyString(list, attrTag);
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmPredictionBreastCancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmPredictionBreastCancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmPredictionBreastCancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmPredictionBreastCancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmPredictionBreastCancer().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorraPaciente;
    private javax.swing.JButton btnClasificaPatologia;
    private javax.swing.JButton btnDetectaContorno;
    private javax.swing.JButton btnMostrarImagen;
    private javax.swing.JButton btnNuevoPaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jtDirecorioDICOM;
    private javax.swing.JTextArea jtaDatosDICOM;
    private javax.swing.JLabel lblDirectorio;
    private javax.swing.JLabel lblElemento;
    private javax.swing.JLabel lblGioDeveloment;
    private javax.swing.JLabel lblIconDICOM;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblSistema;
    // End of variables declaration//GEN-END:variables
}
