/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package segtoolpredictionbreastcancer;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ingenieria
 */
public class frmSesion extends javax.swing.JFrame {
    
    private static Scanner sc;
    private static int intento;
    private static String user, pwd;

    /**
     * Creates new form frmSesion
     */
    public frmSesion() {
        initComponents();
        setLocationRelativeTo(null);
        rootPane.setDefaultButton(btnIngresar);
        rsscalelabel.RSScaleLabel.setScaleLabel(lblBanner, "src/iconos/Mamografia.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblLogoSesion,"src/iconos/LogoSistema.png");
    }

    public static void setIntento(int intento) {
        frmSesion.intento = intento;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUsu = new javax.swing.JLabel();
        lblPwd = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        txtPwd = new javax.swing.JPasswordField();
        lblBanner = new javax.swing.JLabel();
        lblLogoSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de Sesión");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Inicio de Sesión"));
        jPanel1.setLayout(null);

        lblUsu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsu.setText("Usuario");
        jPanel1.add(lblUsu);
        lblUsu.setBounds(340, 180, 130, 17);

        lblPwd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPwd.setText("Password");
        jPanel1.add(lblPwd);
        lblPwd.setBounds(340, 250, 140, 17);

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(204, 204, 204));
        txtUser.setText("Ingresa el Usuario");
        txtUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });
        jPanel1.add(txtUser);
        txtUser.setBounds(340, 200, 180, 30);

        btnCancelar.setBackground(new java.awt.Color(135, 164, 195));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(320, 330, 100, 23);

        btnIngresar.setBackground(new java.awt.Color(135, 164, 195));
        btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar);
        btnIngresar.setBounds(470, 330, 100, 23);

        txtPwd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPwd.setForeground(new java.awt.Color(204, 204, 204));
        txtPwd.setText("Ingresa el Password");
        txtPwd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtPwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPwdMouseClicked(evt);
            }
        });
        jPanel1.add(txtPwd);
        txtPwd.setBounds(340, 270, 180, 30);

        lblBanner.setBackground(new java.awt.Color(135, 164, 195));
        lblBanner.setOpaque(true);
        jPanel1.add(lblBanner);
        lblBanner.setBounds(10, 20, 250, 360);
        jPanel1.add(lblLogoSesion);
        lblLogoSesion.setBounds(320, 20, 190, 130);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        FileReader fr = null;
        try {
            int numLinea = 0, i = 0;
            String [] usuarios = null;
            String linea;
            sc = new Scanner(new File("Usuario/usuarios.txt"));
            File f = new File("Usuario/usuarios.txt");
            fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            
                try {
                    while ((linea = br.readLine())!=null) {
                        numLinea++;

                    }
                } catch (IOException ex) {
                    Logger.getLogger(frmSesion.class.getName()).log(Level.SEVERE, null, ex);
                }
           
            usuarios = new String[numLinea];
            
            while (sc.hasNextLine()) {
                usuarios[i++]=sc.nextLine();
                
            }
            
            intento ++;
            user = txtUser.getText();
            pwd = txtPwd.getText();
            
            seguridadLogin sL = new seguridadLogin();
            sL.validaUsuario(usuarios, user, pwd, intento);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmSesion.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fr.close();
            } catch (IOException ex) {
                Logger.getLogger(frmSesion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        if(intento==0)this.dispose();
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        // TODO add your handling code here:
        txtUser.setText("");
    }//GEN-LAST:event_txtUserMouseClicked

    private void txtPwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPwdMouseClicked
        // TODO add your handling code here:
        txtPwd.setText("");
    }//GEN-LAST:event_txtPwdMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmSesion().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblLogoSesion;
    private javax.swing.JLabel lblPwd;
    private javax.swing.JLabel lblUsu;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
